"use client";

/**
 * /auditor/export-centre — FC-12 §17a, the audit evidence pack.
 *
 * WHAT THIS SCREEN WAS. A seven-item contents list with no counts, five
 * "Generated Packs" rows (AUD-PACK-2026-0042 … 0028, generated by fatima.malik
 * and auditor.external, "3 files", "Ready", downloadable as aud_pack_0042.zip),
 * four export buttons that did nothing, a Schedule Export button for a
 * scheduler that does not exist, and a Generate button whose only effect was a
 * toast reading "Audit pack generated successfully". Nothing was generated. A
 * downloadable evidence zip that does not exist is the most concretely false
 * thing this product could put in front of an auditor, because the artefact IS
 * the deliverable on this screen.
 *
 * WHAT IT IS NOW. §17a bundles the outputs of §16, §17 and §06, and all three
 * are now real, so the pack's CONTENTS are countable exactly: this screen
 * computes the manifest — how many records each section would hold, per node,
 * with the function behind each count — and says plainly that no file is
 * written. Two of the seven sections cannot be fed at all and are marked on the
 * row rather than dropped, because a section missing silently from an evidence
 * pack is worse than one marked unavailable.
 *
 * The filters that survive are the ones that mean something: pack scope, node,
 * and an optional single consignment. Portal, module and the "inc./exc" scope
 * tag are gone — no record in the domain carries any of the three — and the
 * date range is gone because every fixture is one instant.
 */

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  Archive,
  FileStack,
  Package,
  ShieldQuestion,
} from "lucide-react";
import { HqCard, NotAvailable, SeverityPill } from "@/components/hq/HqUi";
import { DEMO_NOW, SITES, formatDateTime, listAwbs, type SiteScope } from "@/lib/domain";
import { AuditorStat } from "../AuditorUi";
import { TRAIL_REGISTERS } from "../auditorMetrics";
import { PACK_SCOPE_LABEL, packManifest, type PackScope } from "../packModel";

const SCOPE_OPTIONS: Array<{ value: SiteScope; label: string }> = [
  { value: "HQ", label: "All nodes" },
  ...SITES.map((s) => ({ value: s.code as SiteScope, label: `${s.code} only` })),
];

export default function ExportCentreContent() {
  const [packScope, setPackScope] = useState<PackScope>("full");
  const [site, setSite] = useState<SiteScope>("HQ");
  const [awbId, setAwbId] = useState<number | null>(null);

  const awbs = useMemo(() => listAwbs({ scope: site }), [site]);
  const manifest = useMemo(
    () => packManifest(packScope, site, awbId),
    [packScope, site, awbId],
  );

  return (
    <div className="space-y-6">
      {/* ---- What goes in the pack -------------------------------------- */}
      <div className="rounded-[14px] border border-[#E2E8F0] bg-white p-5 shadow-sm">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          <div>
            <label className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-[#64748B]">
              Pack scope
            </label>
            <select
              value={packScope}
              onChange={(e) => setPackScope(e.target.value as PackScope)}
              className="h-9 w-full rounded-lg border border-[#E2E8F0] bg-white pl-3 pr-8 text-[12px] text-[#0F172A] outline-none focus:border-[#2E75B6]"
            >
              {(Object.keys(PACK_SCOPE_LABEL) as PackScope[]).map((s) => (
                <option key={s} value={s}>
                  {PACK_SCOPE_LABEL[s]}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-[#64748B]">
              Node
            </label>
            <select
              value={site}
              onChange={(e) => {
                setSite(e.target.value as SiteScope);
                setAwbId(null);
              }}
              className="h-9 w-full rounded-lg border border-[#E2E8F0] bg-white pl-3 pr-8 text-[12px] text-[#0F172A] outline-none focus:border-[#2E75B6]"
            >
              {SCOPE_OPTIONS.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-[#64748B]">
              Narrow to one consignment
            </label>
            <select
              value={awbId ?? ""}
              onChange={(e) => setAwbId(e.target.value === "" ? null : Number(e.target.value))}
              className="h-9 w-full rounded-lg border border-[#E2E8F0] bg-white pl-3 pr-8 text-[12px] text-[#0F172A] outline-none focus:border-[#2E75B6]"
            >
              <option value="">Every consignment in scope ({awbs.length})</option>
              {awbs.map((a) => (
                <option key={a.AWBId} value={a.AWBId}>
                  {a.AWBNO} — {a.site} · {a.stage}
                </option>
              ))}
            </select>
          </div>
        </div>

        <p className="mt-3 max-w-[96ch] text-[11px] leading-relaxed text-[#64748B]">
          <span className="font-semibold text-[#475569]">No date range, and no portal or module
          filter. </span>
          Every fixture in this build is one snapshot at {formatDateTime(DEMO_NOW)}, so a from/to
          range would filter nothing; and no record in the domain carries a portal, a module or the
          demo&apos;s inc./exc scope tag, so those three selectors were choosing between values
          that do not exist on anything they would have filtered.
        </p>
      </div>

      {/* ---- Manifest figures -------------------------------------------- */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <AuditorStat
          label="Records in this pack"
          value={manifest.totalRecords.toLocaleString("en-PK")}
          detail={`${PACK_SCOPE_LABEL[manifest.scope]} · ${site === "HQ" ? "all three nodes" : site}${awbId ? " · one consignment" : ""}`}
          source="packManifest(scope, site, awbId).totalRecords"
        />
        <AuditorStat
          label="Sections that can be filled"
          value={`${manifest.sections.filter((s) => s.included && s.count !== null).length} of ${manifest.sections.filter((s) => s.included).length}`}
          detail="The rest are listed below with the reason, not dropped — a section missing silently from an evidence pack is worse than one marked unavailable."
          source="packManifest(...).sections[].count === null"
          severity={manifest.unavailable > 0 ? "warning" : "good"}
          status={manifest.unavailable > 0 ? `${manifest.unavailable} unavailable` : "complete"}
        />
        <AuditorStat
          label="Files produced"
          value="0"
          detail="Nothing in this build writes a PDF, a CSV, an XLSX or a zip. The manifest below is the deliverable this screen can honestly hand over."
          source="no writer — stated rather than simulated"
          severity="neutral"
        />
      </div>

      {/* ---- The manifest -------------------------------------------------- */}
      <HqCard
        title="Pack manifest"
        icon={Package}
        source="packManifest(scope, site, awbId) · components/auditor/packModel.ts"
        intro="What the pack would contain, counted from the same functions the three screens above render. FC-12 §17a bundles §16, §17 and §06 — so this card imports those three models rather than re-querying, and the dependency is the flow's own."
      >
        <div className="flex flex-col gap-3">
          {manifest.sections.map((s) => (
            <div
              key={s.key}
              className="rounded-[12px] border px-4 py-3"
              style={{
                borderColor: s.count === null ? "#CBD5E1" : "#E2E8F0",
                borderStyle: s.count === null ? "dashed" : "solid",
                backgroundColor: s.included ? "#F8FAFC" : "white",
                opacity: s.included ? 1 : 0.55,
              }}
            >
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                <span className="text-[13px] font-semibold text-[#0F172A]">{s.label}</span>
                {s.count === null ? (
                  <SeverityPill severity="warning" label="Cannot be filled" />
                ) : s.included ? (
                  <span className="text-[15px] font-bold tabular-nums text-[#0F172A]">
                    {s.count.toLocaleString("en-PK")}{" "}
                    <span className="text-[11px] font-medium text-[#64748B]">{s.unit}</span>
                  </span>
                ) : (
                  <SeverityPill severity="neutral" label="Out of scope" />
                )}
              </div>
              <p className="mt-1.5 text-[11px] leading-relaxed text-[#64748B]">{s.detail}</p>
              {s.reason && (
                <p className="mt-1.5 text-[11px] leading-relaxed text-[#B45309]">{s.reason}</p>
              )}
              <p className="mt-1.5 font-mono text-[10px] text-[#94A3B8]">{s.source}</p>
            </div>
          ))}
        </div>

        <div className="mt-4 rounded-[12px] border border-[#E2E8F0] bg-white px-4 py-3">
          <p className="text-[12px] font-semibold text-[#0F172A]">
            Where each section is rendered today
          </p>
          <p className="mt-1.5 text-[11px] leading-relaxed text-[#64748B]">
            The pack has no file behind it, but every section that CAN be filled is already on
            screen and drillable:{" "}
            <Link
              href="/auditor/cargo-trace"
              className="font-semibold text-[#1B4F8B] no-underline hover:underline"
            >
              cargo trace
            </Link>{" "}
            (§16),{" "}
            <Link
              href="/auditor/financial-trace"
              className="font-semibold text-[#1B4F8B] no-underline hover:underline"
            >
              financial trace
            </Link>{" "}
            (§17),{" "}
            <Link
              href="/auditor/rbac-snapshot"
              className="font-semibold text-[#1B4F8B] no-underline hover:underline"
            >
              RBAC snapshot
            </Link>{" "}
            (§06) and the record trail on the{" "}
            <Link
              href="/auditor"
              className="font-semibold text-[#1B4F8B] no-underline hover:underline"
            >
              auditor home
            </Link>
            . An auditor can obtain every figure in this manifest; what they cannot do is receive
            it as one downloadable artefact.
          </p>
        </div>
      </HqCard>

      {/* ---- Gaps ---------------------------------------------------------- */}
      <HqCard
        title="Not shown on this screen, and why"
        icon={ShieldQuestion}
        source="no fixture — stated rather than estimated"
        intro="Four things this screen displayed. None of them has a store, a writer or a scheduler behind it."
      >
        <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
          <NotAvailable
            title="Previously generated packs"
            reason="There is no pack store. The five rows here — AUD-PACK-2026-0042, 0038, 0035, 0031, 0028, with generation dates spanning April to June, file counts, Ready badges and downloadable zips — were a component-local array, and every zip they offered was a filename with nothing behind it. Because nothing has ever been generated, the honest register is empty, and an empty register is what this says rather than five rows of history that never happened."
            nearest="The manifest above, recomputed from the registers each time this screen is opened — which is what a pack would be a snapshot of."
          />
          <NotAvailable
            title="Download as PDF, CSV, XLSX or zip"
            reason="Nothing in this build writes a file. The four export buttons produced no bytes, and the Generate button raised a toast reading 'Audit pack generated successfully' — a success message for an act that did not occur, on the one screen where the artefact is the point."
            nearest="The manifest, which states exactly what a real export would contain and how many records each section would hold."
          />
          <NotAvailable
            title="Scheduled exports"
            reason="No scheduler, no job store and no delivery channel for a scheduled artefact. A recurring export of a file that cannot be written has nothing to recur."
            nearest="Nothing — this one is simply out of scope, and saying so is more useful than a button that opens a dialog and forgets."
          />
          <NotAvailable
            title="System event logs, and who exported what"
            reason="There is no audit-event store, so the pack's seventh section cannot be filled and this screen cannot record its own use either. An evidence pack that silently omits the event log is a pack whose recipient does not know it is missing."
            nearest={`The record trail on the auditor home — every WRITE with a timestamp and an actor, from the ${TRAIL_REGISTERS.length} registers that carry both. It holds no reads, no logins and no exports, and says so.`}
          />
        </div>
      </HqCard>

      {/* ---- Provenance strip ------------------------------------------- */}
      <div className="flex flex-wrap items-center gap-x-4 gap-y-2 rounded-[14px] border border-[#E2E8F0] bg-white px-5 py-3.5 shadow-sm">
        <div className="flex items-center gap-2">
          <Archive size={15} className="text-[#64748B]" />
          <span className="text-[12px] font-semibold text-[#0F172A]">
            FC-12 §17a — audit evidence pack
          </span>
        </div>
        <div className="flex items-center gap-2">
          <FileStack size={14} className="text-[#94A3B8]" />
          <span className="text-[11px] text-[#64748B]">
            Bundles §16 cargo timeline, §17 financial timeline and §06 RBAC snapshot — the three
            models this screen imports rather than re-queries.
          </span>
        </div>
      </div>
    </div>
  );
}
