/**
 * The audit evidence pack — FC-12 §17a.
 *
 * §17a is the only step in the Audit & reporting lane that is not a view: it
 * "bundles their outputs — cargo timeline, financial timeline, RBAC snapshot,
 * evidence, event logs". So this module imports the other three models rather
 * than re-querying the domain, and the dependency is the flow's own: a pack is
 * §16 plus §17 plus §06, counted.
 *
 * WHAT WAS HERE BEFORE. A seven-item contents list with no counts, five
 * "Generated Packs" rows (AUD-PACK-2026-0042 and friends, generated by
 * fatima.malik and auditor.external, "3 files", "Ready", aud_pack_0042.zip) and
 * a Generate button whose only effect was a toast reading "Audit pack generated
 * successfully". Nothing was generated, no pack store exists, and a downloadable
 * zip that does not exist is the most concretely false thing a demo can put in
 * front of an auditor — it is the artefact the whole screen is about.
 *
 * WHAT IS TRUE INSTEAD. The pack's CONTENTS are computable exactly, because
 * every section is a real query: the manifest below counts the records each
 * section would contain, per node, and names the function that produced each
 * count. That is a real deliverable — a client can read it and see the pack is
 * not empty — and it does not claim a file. Two of the seven sections cannot be
 * fed at all and say so on the row rather than being dropped, because a section
 * silently missing from an evidence pack is worse than one marked unavailable.
 */

import {
  DEMO_NOW,
  SITES,
  listAwbs,
  listCdrs,
  listDocuments,
  listInvoices,
  type SiteScope,
} from "@/lib/domain";
import { cargoTrace, financialTrace } from "./traceModel";
import { rbacSnapshot } from "./rbacModel";

export type PackScope = "full" | "cargo" | "financial" | "rbac";

export const PACK_SCOPE_LABEL: Record<PackScope, string> = {
  full: "Full — cargo, financial and access",
  cargo: "Cargo only",
  financial: "Financial only",
  rbac: "RBAC snapshot only",
};

export interface PackSection {
  key: string;
  label: string;
  /** Null where the section cannot be fed — then `reason` says why. */
  count: number | null;
  unit: string;
  /** The lib/domain path behind the count, verbatim. */
  source: string;
  detail: string;
  reason?: string;
  included: boolean;
}

export interface PackManifest {
  scope: PackScope;
  site: SiteScope;
  /** Set when the pack is narrowed to one consignment. */
  awbId: number | null;
  sections: PackSection[];
  totalRecords: number;
  unavailable: number;
}

const NODE_LABEL = (site: SiteScope) =>
  site === "HQ" ? `all ${SITES.length} nodes` : `${site} only`;

export function packManifest(
  scope: PackScope,
  site: SiteScope,
  awbId: number | null,
): PackManifest {
  const wantsCargo = scope === "full" || scope === "cargo";
  const wantsFinance = scope === "full" || scope === "financial";
  const wantsRbac = scope === "full" || scope === "rbac";

  /* --- §16, once per consignment in scope --------------------------- */
  const awbs = awbId
    ? listAwbs({ scope: site }).filter((a) => a.AWBId === awbId)
    : listAwbs({ scope: site });
  const traces = awbs.map((a) => cargoTrace(a.AWBId)).filter((t) => t !== null);
  const cargoEvents = traces.reduce((n, t) => n + t.events.length, 0);

  /* --- §17, once per invoice in scope ------------------------------- */
  const invoices = awbId
    ? listInvoices(site).filter((i) => i.awbId === awbId)
    : listInvoices(site);
  const financeTraces = invoices
    .map((i) => financialTrace(i.invoiceNo))
    .filter((t) => t !== null);
  const financeEvents = financeTraces.reduce((n, t) => n + t.events.length, 0);

  /* --- §06 ----------------------------------------------------------- */
  const rbac = rbacSnapshot(DEMO_NOW, site);

  /* --- Evidence and documents ---------------------------------------- */
  const docs = awbId
    ? listDocuments(site).filter((d) => d.awbId === awbId)
    : listDocuments(site);
  const cdrs = awbId
    ? listCdrs(site).filter((c) => c.awbId === awbId)
    : listCdrs(site);
  const evidenceItems = cdrs.reduce((n, c) => n + c.evidence.length, 0);

  const sections: PackSection[] = [
    {
      key: "summary",
      label: "Summary PDF",
      count: null,
      unit: "",
      source: "no renderer — nothing in this build writes a PDF",
      detail:
        "Every other section below is a count this screen can already produce; the cover sheet is the one part that needs a document renderer, and there is none.",
      reason: "No PDF or file writer exists in the demo. Nothing is downloadable from this screen.",
      included: wantsCargo || wantsFinance || wantsRbac,
    },
    {
      key: "cargo",
      label: "Cargo timeline",
      count: wantsCargo ? cargoEvents : 0,
      unit: "dated events",
      source: "cargoTrace(awbId).events · components/auditor/traceModel.ts",
      detail: wantsCargo
        ? `Across ${traces.length} ${traces.length === 1 ? "consignment" : "consignments"} in ${NODE_LABEL(site)} — the same timeline /auditor/cargo-trace draws, one per AWB.`
        : "Not part of this pack scope.",
      included: wantsCargo,
    },
    {
      key: "financial",
      label: "Financial timeline",
      count: wantsFinance ? financeEvents : 0,
      unit: "dated events",
      source: "financialTrace(invoiceNo).events · components/auditor/traceModel.ts",
      detail: wantsFinance
        ? `Across ${financeTraces.length} ${financeTraces.length === 1 ? "invoice" : "invoices"} in ${NODE_LABEL(site)}, with the charge calculation and every approval decision behind each.`
        : "Not part of this pack scope.",
      included: wantsFinance,
    },
    {
      key: "rbac",
      label: "User access snapshot",
      count: wantsRbac ? rbac.rows.length : 0,
      unit: "grant rows",
      source: "rbacSnapshot(DEMO_NOW, site).rows · components/auditor/rbacModel.ts",
      detail: wantsRbac
        ? `${rbac.principals} principals, ${rbac.inForce} in force, ${rbac.capped} rows where the requested depth did not survive the HQ ceiling.`
        : "Not part of this pack scope.",
      included: wantsRbac,
    },
    {
      key: "evidence",
      label: "Supporting evidence",
      count: wantsCargo ? evidenceItems : 0,
      unit: "evidence items",
      source: "listCdrs(site) · CDR.evidence[] · lib/domain/index.ts",
      detail: wantsCargo
        ? `Photo, weight, piece-count, package-condition, seal-condition and remarks items attached to ${cdrs.length} discrepancy ${cdrs.length === 1 ? "report" : "reports"}, each RFID- or AWB-linked and timestamped.`
        : "Not part of this pack scope.",
      included: wantsCargo,
    },
    {
      key: "documents",
      label: "Uploaded documents",
      count: docs.length,
      unit: "documents",
      source: "listDocuments(site) · lib/domain/documents.ts",
      detail: `${docs.reduce((n, d) => n + d.pages, 0)} pages, ${Math.round(docs.reduce((n, d) => n + d.sizeKb, 0) / 1024)} MB · ${docs.filter((d) => d.versions.length > 1).length} carry a superseded earlier version, which is what makes a document trail defensible.`,
      /* An access-only pack does not carry the cargo document store — the
         grant register has no documents attached to it. */
      included: wantsCargo || wantsFinance,
    },
    {
      key: "events",
      label: "System event logs",
      count: null,
      unit: "",
      source: "no store — there is no audit-event table in lib/domain",
      detail:
        "The nearest real thing is on the auditor home: every write in the demo that carries both a timestamp and an actor column, gathered from the twelve registers that have them. That is a record trail, not an event log — it holds no reads, no logins and no exports.",
      reason:
        "Nothing records who VIEWED or EXPORTED anything, at any tier. /admin/audit-trail renders a component-local array with no date, no site column and no severity field, so it cannot supply this section either.",
      included: true,
    },
  ];

  const totalRecords = sections
    .filter((s) => s.included && s.count !== null)
    .reduce((n, s) => n + (s.count ?? 0), 0);

  return {
    scope,
    site,
    awbId,
    sections,
    totalRecords,
    unavailable: sections.filter((s) => s.included && s.count === null).length,
  };
}
